import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-02.
 *
 * Steps:
 *   1. Open http://localhost:5173/settings
 *   2. Click button "清除所有学习数据"
 *   3. Expect "确定要清除吗？此操作无法撤销！" to be visible
 *   4. Click button "取消"
 *   5. Expect heading "设置" to be visible
 *   6. Expect button "清除所有学习数据" to be visible
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 */
test('Cancel reset data confirmation', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/settings", async () => {
    await page.goto("/settings");
  });
  await test.step("When · Click button \"清除所有学习数据\"", async () => {
    const el = page.getByRole("button", { name: "清除所有学习数据", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Expect \"确定要清除吗？此操作无法撤销！\" to be visible", async () => {
    await expect(page.getByText("确定要清除吗？此操作无法撤销！").first()).toBeVisible();
  });
  await test.step("When · Click button \"取消\"", async () => {
    const el = page.getByRole("button", { name: "取消", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Expect heading \"设置\" to be visible", async () => {
    await expect(page.getByRole("heading", { name: "设置", exact: true }).first()).toBeVisible();
  });
  await test.step("When · Expect button \"清除所有学习数据\" to be visible", async () => {
    await expect(page.getByRole("button", { name: "清除所有学习数据", exact: true }).first()).toBeVisible();
  });
});
