import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-03.
 *
 * Steps:
 *   1. Open http://localhost:5173/settings
 *   2. Click button "免登录体验 稍后可绑定邮箱同步数据"
 *   3. Click button "Get Started"
 *   4. Click button "🇨🇳 中文"
 *   5. Click button "下一步"
 *   6. Click button "20 个单词 适中"
 *   7. Click button "开始学习"
 *   8. Open http://localhost:5173/settings
 *   9. Click button "清除所有学习数据"
 *   10. Expect "确定要清除吗？此操作无法撤销！" to be visible
 *   11. Click button "取消"
 *   12. Expect heading "设置" to be visible
 *   13. Expect button "清除所有学习数据" to be visible
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 */
test('Cancel reset data confirmation', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/settings", async () => {
    await page.goto("/settings");
  });
  await test.step("When · Click button \"免登录体验 稍后可绑定邮箱同步数据\"", async () => {
    const el = page.getByRole("button", { name: "免登录体验 稍后可绑定邮箱同步数据", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"Get Started\"", async () => {
    const el = page.getByRole("button", { name: "Get Started", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"🇨🇳 中文\"", async () => {
    const el = page.getByRole("button", { name: "🇨🇳 中文", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"下一步\"", async () => {
    const el = page.getByRole("button", { name: "下一步", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"20 个单词 适中\"", async () => {
    const el = page.getByRole("button", { name: "20 个单词 适中", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"开始学习\"", async () => {
    const el = page.getByRole("button", { name: "开始学习", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Open http://localhost:5173/settings", async () => {
    await page.goto("/settings");
  });
  await test.step("When · Click button \"清除所有学习数据\"", async () => {
    const el = page.getByRole("button", { name: "清除所有学习数据", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Expect \"确定要清除吗？此操作无法撤销！\" to be visible", async () => {
    await expect(page.getByText("确定要清除吗？此操作无法撤销！").first()).toBeVisible();
  });
  await test.step("When · Click button \"取消\"", async () => {
    const el = page.getByRole("button", { name: "取消", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Expect heading \"设置\" to be visible", async () => {
    await expect(page.getByRole("heading", { name: "设置", exact: true }).first()).toBeVisible();
  });
  await test.step("When · Expect button \"清除所有学习数据\" to be visible", async () => {
    await expect(page.getByRole("button", { name: "清除所有学习数据", exact: true }).first()).toBeVisible();
  });
});
