import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-02.
 *
 * Steps:
 *   1. Open http://localhost:5173/settings
 *   2. Click button "50 个单词"
 *   3. Open http://localhost:5173/stats
 *   4. Expect "50" to be visible
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 */
test('Change daily goal', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/settings", async () => {
    await page.goto("/settings");
  });
  await test.step("When · Click button \"50 个单词\"", async () => {
    const el = page.getByRole("button", { name: "50 个单词", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Open http://localhost:5173/stats", async () => {
    await page.goto("/stats");
  });
  await test.step("When · Expect \"50\" to be visible", async () => {
    await expect(page.getByText("50").first()).toBeVisible();
  });
});
