import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-04.
 *
 * Steps:
 *   1. Open http://localhost:5173/login
 *   2. Click button "免登录体验 稍后可绑定邮箱同步数据"
 *   3. Click button "Get Started"
 *   4. Click button "Next"
 *   5. Click button "Start Learning"
 *   6. Open http://localhost:5173/settings
 *   7. Click button "50 words"
 *   8. Expect the "50 words" goal to be selected
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 *
 * HEALING NOTES (2026-07-04):
 *   Step 5 "Start Learning" (daily-goal onboarding) drifted: the recorded
 *   grounded locator was the exact Chinese label "开始学习", but the onboarding
 *   now renders in English, so it no longer located. Re-grounded to the English
 *   "Start Learning" against the live app; the rest of the flow was unchanged.
 *   The final step keeps its selection assertion (clay-btn-primary) rather than
 *   a plain visibility check, so the test still verifies the goal took effect.
 */
test('Change daily goal', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/login", async () => {
    await page.goto("/login");
  });
  await test.step("When · Click button \"免登录体验 稍后可绑定邮箱同步数据\"", async () => {
    const el = page.getByRole("button", { name: "免登录体验 稍后可绑定邮箱同步数据", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"Get Started\"", async () => {
    const el = page.getByRole("button", { name: "Get Started", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"Next\"", async () => {
    const el = page.getByRole("button", { name: "Next", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"Start Learning\"", async () => {
    const el = page.getByRole("button", { name: "Start Learning", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Open http://localhost:5173/settings", async () => {
    await page.goto("/settings");
  });
  await test.step("When · Click button \"50 words\"", async () => {
    const el = page.getByRole("button", { name: "50 words", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("Then · Expect the \"50 words\" goal to be selected", async () => {
    // The selected goal is marked with the clay-btn-primary style. Asserting
    // selection (not mere visibility, which holds regardless of the goal)
    // preserves this spec's intent: confirm the change actually took effect.
    const el = page.getByRole("button", { name: "50 words", exact: true }).first();
    await expect(el).toHaveClass(/clay-btn-primary/, { timeout: 8000 });
  });
});
