import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-03.
 *
 * Steps:
 *   1. Open http://localhost:5173/login
 *   2. Click button "免登录体验 稍后可绑定邮箱同步数据"
 *   3. Click button "Get Started"
 *   4. Click button "🇨🇳 中文"
 *   5. Click button "下一步"
 *   6. Click button "10 个单词 轻松"
 *   7. Click button "开始学习"
 *   8. Open http://localhost:5173/settings
 *   9. Click button "50 个单词"
 *   10. Open http://localhost:5173/stats
 *   11. Expect "50" to be visible
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 */
test('Change daily goal', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/login", async () => {
    await page.goto("/login");
  });
  await test.step("When · Click button \"免登录体验 稍后可绑定邮箱同步数据\"", async () => {
    const el = page.getByRole("button", { name: "免登录体验 稍后可绑定邮箱同步数据", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"Get Started\"", async () => {
    const el = page.getByRole("button", { name: "Get Started", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"🇨🇳 中文\"", async () => {
    const el = page.getByRole("button", { name: "🇨🇳 中文", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"下一步\"", async () => {
    const el = page.getByRole("button", { name: "下一步", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"10 个单词 轻松\"", async () => {
    const el = page.getByRole("button", { name: "10 个单词 轻松", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"开始学习\"", async () => {
    const el = page.getByRole("button", { name: "开始学习", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Open http://localhost:5173/settings", async () => {
    await page.goto("/settings");
  });
  await test.step("When · Click button \"50 个单词\"", async () => {
    const el = page.getByRole("button", { name: "50 个单词", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Open http://localhost:5173/stats", async () => {
    await page.goto("/stats");
  });
  await test.step("When · Expect \"50\" to be visible", async () => {
    await expect(page.getByText("50").first()).toBeVisible();
  });
});
