import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-02.
 *
 * Steps:
 *   1. Open http://localhost:5173/login
 *   2. Expect button "免登录体验 稍后可绑定邮箱同步数据" to be visible
 *   3. Click button "免登录体验 稍后可绑定邮箱同步数据"
 *   4. Expect button "Get Started" to be visible
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 */
test('Log in anonymously', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/login", async () => {
    await page.goto("/login");
  });
  await test.step("When · Expect button \"免登录体验 稍后可绑定邮箱同步数据\" to be visible", async () => {
    await expect(page.getByRole("button", { name: "免登录体验 稍后可绑定邮箱同步数据", exact: true }).first()).toBeVisible();
  });
  await test.step("When · Click button \"免登录体验 稍后可绑定邮箱同步数据\"", async () => {
    const el = page.getByRole("button", { name: "免登录体验 稍后可绑定邮箱同步数据", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Expect button \"Get Started\" to be visible", async () => {
    await expect(page.getByRole("button", { name: "Get Started", exact: true }).first()).toBeVisible();
  });
});
