import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-06-27.
 *
 * Steps:
 *   1. Open http://localhost:5173
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 */
test('Loginwithemail', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173", async () => {
    await page.goto("/");
  });
  await test.step("When · click_control", async () => {
    const el = page.getByRole("link", { name: "设置", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · fill_control", async () => {
    const el = page.getByRole("textbox", { name: "example@email.com", exact: true });
    await expect(el).toBeVisible();
    await el.fill("test@hover.com");
  });
  await test.step("When · fill_control", async () => {
    const el = page.getByRole("textbox", { name: "输入密码", exact: true });
    await expect(el).toBeVisible();
    await el.fill("123456789");
  });
  await test.step("When · click_control", async () => {
    const el = page.getByRole("button", { name: "登录账户", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · assert_visible", async () => {
    await expect(page.getByText("Just synced").first()).toBeVisible();
  });
});
