import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-02.
 *
 * Steps:
 *   1. Open http://localhost:5173/
 *   2. Click "点击卡片查看答案，或按空格键"
 *   3. Expect button "认识" to be visible
 *   4. Click button "认识"
 *   5. Expect "点击卡片查看答案，或按空格键" to be visible
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 */
test('Reveal word answer and respond', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/", async () => {
    await page.goto("/");
  });
  await test.step("When · Click \"点击卡片查看答案，或按空格键\"", async () => {
    const el = page.getByText("点击卡片查看答案，或按空格键").first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Expect button \"认识\" to be visible", async () => {
    await expect(page.getByRole("button", { name: "认识", exact: true }).first()).toBeVisible();
  });
  await test.step("When · Click button \"认识\"", async () => {
    const el = page.getByRole("button", { name: "认识", exact: true });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Expect \"点击卡片查看答案，或按空格键\" to be visible", async () => {
    await expect(page.getByText("点击卡片查看答案，或按空格键").first()).toBeVisible();
  });
});
