import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-02. Healed 2026-07-04.
 *
 * Intent: from a fresh session, reveal a word's answer and respond that you
 * know it ("认识" / "Good"), then confirm the card resets for the next word.
 *
 * Steps:
 *   1. Open http://localhost:5173/login
 *   2. Click button "免登录体验 稍后可绑定邮箱同步数据" (anonymous login)
 *   3. Wait for the post-login sync to settle
 *   4. Click button "Get Started" (onboarding)
 *   5. Click button "Next"          (language step — keep default)
 *   6. Click button "Start Learning" (daily-goal step — keep default)
 *   7. Reveal the answer (press Space — the card's documented reveal action)
 *   8. Expect the "认识 / Good" response button to be visible
 *   9. Click the "认识 / Good" response button
 *  10. Expect the response buttons to clear (card reset for the next word)
 *
 * HEALING NOTES — the app drifted in two ways since the original recording:
 *   (a) A login gate + onboarding wizard (Get Started → language → daily goal)
 *       was inserted before the learn page, so the flow must now traverse it.
 *   (b) Logging in anonymously mints an account whose synced prefs render the
 *       app in ENGLISH, and the sync lands asynchronously ("同步中…"), racing
 *       with — and resetting — local onboarding/language choices. So we wait
 *       for the sync to settle before onboarding, keep onboarding on its
 *       default language, and match the response control by a LANGUAGE-NEUTRAL
 *       locator (regex name, keyboard shortcut) instead of the original
 *       Chinese-only text — the recorded intent, re-grounded to survive locale.
 */
test('Reveal word answer and respond', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/login", async () => {
    await page.goto("/login");
  });
  await test.step("When · Click button \"免登录体验 稍后可绑定邮箱同步数据\"", async () => {
    const el = page.getByRole("button", { name: /免登录体验|without login|Continue without/i }).first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("And · Wait for the post-login sync to settle", async () => {
    // The anonymous account syncs asynchronously; clicking onboarding before
    // it lands gets clobbered (onboarding resets to the first screen). Wait
    // for the network to go idle, then confirm onboarding is stably mounted.
    await page.waitForLoadState("networkidle").catch(() => {});
    await expect(page.getByRole("button", { name: /Get Started|开始/i })).toBeVisible({ timeout: 20000 });
  });
  await test.step("When · Click button \"Get Started\"", async () => {
    const el = page.getByRole("button", { name: /Get Started|开始/i }).first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"Next\" (language step, keep default)", async () => {
    const el = page.getByRole("button", { name: /^(Next|下一步)$/ }).first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"Start Learning\" (daily goal, keep default)", async () => {
    const el = page.getByRole("button", { name: /Start Learning|开始学习/i }).first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Reveal the answer (press Space) and expect the \"认识 / Good\" button", async () => {
    // The card hint reads "click the card, or press Space"; Space is the
    // language-neutral equivalent of the recorded card-click reveal. Retry the
    // press until the answer flips — a lone early press can be dropped before
    // the keyboard handler mounts on the freshly-loaded learn page.
    const good = page.getByRole("button", { name: /^(认识|Good)$/ }).first();
    await expect(async () => {
      await page.keyboard.press("Space");
      await expect(good).toBeVisible({ timeout: 2000 });
    }).toPass({ timeout: 20000 });
  });
  await test.step("When · Click the \"认识 / Good\" response button", async () => {
    const el = page.getByRole("button", { name: /^(认识|Good)$/ }).first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Expect the response buttons to clear (card reset)", async () => {
    // After responding, the card advances to the next word and the rating
    // buttons disappear until the answer is revealed again.
    await expect(page.getByRole("button", { name: /^(认识|Good)$/ })).toHaveCount(0, { timeout: 20000 });
  });
});
