import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-02.
 *
 * Steps:
 *   1. Open http://localhost:5173/stats
 *   2. Expect heading "学习统计" to be visible
 *   3. Expect heading "词汇统计" to be visible
 *   4. Expect heading "CEFR Levels" to be visible
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 */
test('View learning stats', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/stats", async () => {
    await page.goto("/stats");
  });
  await test.step("When · Expect heading \"学习统计\" to be visible", async () => {
    await expect(page.getByRole("heading", { name: "学习统计", exact: true }).first()).toBeVisible();
  });
  await test.step("When · Expect heading \"词汇统计\" to be visible", async () => {
    await expect(page.getByRole("heading", { name: "词汇统计", exact: true }).first()).toBeVisible();
  });
  await test.step("When · Expect heading \"CEFR Levels\" to be visible", async () => {
    await expect(page.getByRole("heading", { name: "CEFR Levels", exact: true }).first()).toBeVisible();
  });
});
