import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-07-03. Healed 2026-07-04.
 *
 * Intent: from a fresh session, reach the Stats page and confirm its three
 * section headings render (learning stats, vocabulary stats, CEFR levels).
 *
 * Steps:
 *   1. Open http://localhost:5173/stats   (fresh session redirects to /login)
 *   2. Click button "免登录体验 稍后可绑定邮箱同步数据" (anonymous login)
 *   3. Wait for the post-login sync to settle
 *   4. Click button "Get Started"          (onboarding)
 *   5. Click button "Next"                  (language step — keep default)
 *   6. Click button "Start Learning"        (daily-goal step — keep default)
 *   7. Open http://localhost:5173/stats
 *   8. Expect heading "学习统计 / Statistics" to be visible
 *   9. Expect heading "词汇统计 / Vocabulary" to be visible
 *  10. Expect heading "CEFR Levels" to be visible
 *
 * HEALING NOTES — same drift as reveal-word-answer-and-respond:
 *   (a) A login gate + onboarding wizard was inserted before the app, so the
 *       flow must traverse it to reach an authenticated session.
 *   (b) Anonymous login mints an account whose synced prefs render the app in
 *       ENGLISH, and the sync lands asynchronously ("同步中…"), racing with and
 *       resetting local onboarding/language choices. So we wait for the sync
 *       to settle before onboarding, keep onboarding on its default language,
 *       and match the two localized headings by a LANGUAGE-NEUTRAL regex
 *       (学习统计→Statistics, 词汇统计→Vocabulary). "CEFR Levels" is hardcoded
 *       English in both locales, so it is matched as-is. The Stats page also
 *       computes over ~3000 words on mount, so headings get a generous timeout.
 */
test('View learning stats', async ({ page }) => {
  await test.step("Given · Open http://localhost:5173/stats", async () => {
    await page.goto("/stats");
  });
  await test.step("When · Click button \"免登录体验 稍后可绑定邮箱同步数据\"", async () => {
    const el = page.getByRole("button", { name: /免登录体验|without login|Continue without/i }).first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("And · Wait for the post-login sync to settle", async () => {
    await page.waitForLoadState("networkidle").catch(() => {});
    await expect(page.getByRole("button", { name: /Get Started|开始/i })).toBeVisible({ timeout: 20000 });
  });
  await test.step("When · Click button \"Get Started\"", async () => {
    const el = page.getByRole("button", { name: /Get Started|开始/i }).first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"Next\" (language step, keep default)", async () => {
    const el = page.getByRole("button", { name: /^(Next|下一步)$/ }).first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click button \"Start Learning\" (daily goal, keep default)", async () => {
    const el = page.getByRole("button", { name: /Start Learning|开始学习/i }).first();
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Open http://localhost:5173/stats", async () => {
    await page.waitForLoadState("networkidle").catch(() => {});
    await page.goto("/stats");
  });
  await test.step("When · Expect heading \"学习统计 / Statistics\" to be visible", async () => {
    await expect(page.getByRole("heading", { name: /^(学习统计|Statistics)$/ }).first()).toBeVisible({ timeout: 20000 });
  });
  await test.step("When · Expect heading \"词汇统计 / Vocabulary\" to be visible", async () => {
    await expect(page.getByRole("heading", { name: /^(词汇统计|Vocabulary)$/ }).first()).toBeVisible({ timeout: 20000 });
  });
  await test.step("When · Expect heading \"CEFR Levels\" to be visible", async () => {
    await expect(page.getByRole("heading", { name: /^(CEFR 等级|CEFR Levels)$/ }).first()).toBeVisible({ timeout: 20000 });
  });
});
